### PR TITLE
Bump stunnel version.

### PR DESCRIPTION
**Pull request by UserNotFound**
Mirrors the change we made here to eliminate false memory leak log lines: https://github.com/aptible/docker-redis/pull/35

### CODE REVIEW

**Comment by almathew** [comment]
I'm slightly concerned about this because I don't think we have any stunnel tests, or anything that tests connecting over stunnel. While I doubt the version bump would break this functionality, it would be nice to confirm.

Do you know of any tests?

**Comment by UserNotFound** [comment]
>While I doubt the version bump would break this functionality, it would be nice to confirm.

Are there no integration tests that test `aptible logs`, or ones that test JC to GJ connectivity already?

>Do you know of any tests?

No, I had the same concern when updating stunnel in docker-redis: a specific version had been selected previously, but there were no tests created at that time that would prevent a future regression of whatever the criteria were for choosing that version.  

 Using this proposed version of stunnel feels as reasonable even without tests, given all of our customers have been using it for a year with various Redis clients.

**Comment by almathew** [comment]
> Are there no integration tests that test aptible logs, or ones that test JC to GJ connectivity already?

There are tests in `aptible-integration`, however this change would go live before we tested that.

**Comment by UserNotFound** [comment]
Can we... build this and publish the image as a new tag (eg aptible/gentlemanjerry:pr45) and then make a draft PR for aptible-ingegration to use this for sweetness.env.GENTLEMAN_JERRY_IMAGE  just so that it's tested?

**Review by almathew — APPROVED** [review]
Confirmed this works on the aptible-dev-satellite stack. Feel free to test/check out kibana yourself.
I'll switch that stack back to the default v2 image tomorrow afternoon.

**Pull request merged**
